"""
This is a setup.py script generated by py2applet

Usage:
    python py2app-record.py py2app
"""

from setuptools import setup

APP = ['recordgui.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': False}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
